### ISSUE TITLE
Wireless controller support

### ISSUE THREAD

**Issue by joncoop** [joncoop/pygame-xbox360controller#1]
On Linux, only wired controllers use axes for the hat, wireless use buttons. Wireless support is not included yet. I don't have a wireless controller to use for testing, but will add support when I get a hold of one.

**Comment by ghost** [comment]
I could do a wireless controller test for you, because I do not have wired controller, only wireless ones. The wireless ones are connected to an adapter, and it can support multiple controllers. I will post what I can find.

**Comment by joncoop** [comment]
Very cool. Fork the repo, and I'll try to merge your changes when you're
done. I know the code is a bit clunky in the **init()** with all the ifs,
but keep that same structure for your additions. I don't know much about
merging, so I want the code to be as similar as possible to help me see
changes and resolve conflicts easily. It should be good git practice for
both of us.

Later on, I do plan on adding some sort of configuration section (perhaps a
dict) to store controller mapping. I've also been looking at decorators to
simplify usage. (This code still feels a bit like Java with getter methods.
I'm working on being more Pythonic.)

**Comment by ghost** [comment]
Have you checked out my PyNotes repository? I have only been doing python(and a bit of c++) and you can look at my structuring for that. Also tell Nathan I said hello.

For multiple controllers I recommend that you use a key mapping class for it, or something along that line.

**Comment by ghost** [comment]
Wireless support works!
    The joystick name is set to:
       Controller (Xbox 360 Wireless Receiver for Windows)

I know that you set the right joystick to go along with the pygame window, but from a gamer's perspective, I HIGHLY recommend inverting that, or atleast include an inverting feature in the controller class. Please look at the fork as soon as you can, maybe during a class change.

I intend to give you a gamer's perspective on this: as someone who programs python, and also has been using the Xbox 360 Controller for years as well.

I have yet to test with a different controller..

**Comment by joncoop** [comment]
What do you mean, right stick? Are you looking in the simple game class where I somewhat arbitrarily decided to move the little ball around with the left stick? I kind of figured that player movement would typically be handled by the left stick so the right thumb could be freed up to shoot stuff or whatever the buttons do. Is this not the case? My gaming experience is pretty much limited to Mario games and Tetris.

**Comment by ghost** [comment]
Check the fork, I just updated it!

A lot of games often have the "right stick inverted" option, so that is what my concern was. The right stick is naturally inverted, at least I think.

All I did was add a right stick ball, so you will see what I mean...

UPDATE(10:02)
Now the right stick is not inverted, because I switched it in the xbox controller class. I implemented the inverted feature that can be seen in the simple game template. look at both the controller class and the template file.

**Comment by joncoop** [comment]
You mean I need to switch axes 3 & 4, right? I think I had them correct at one point. Must have lost the flip during an update & going back and forth between linux at home and windows at work.

**Comment by ghost** [comment]
I  just finished a little game that can be expanded upon. you should check it out, I just posted it in my fork.
controls for it in the description

**Comment by ghost** [comment]
Multi-Controller Wireless set up works properly!!!!!

syntax:

p1_controller = XBox360Controller(0)
p2_controller = XBox360Controller(1)

then assign different keys

a_btn_1 = p1_controller.a()
a_btn_2 = p2_controller.a()

They work flawlessly, but if there is not an active joystick, then it raises an error. I plan to fix said error by implementing a controller detection feature on start up: automatically assigning the controllers based on which joystick name they are. In the occurrence that a controller turns off during gameplay, The program will raise an error or event signaling that the joystick has been disconnected.

**Comment by ghost** [comment]
Also, this does work on windows 10, as that is the system that I am using now

**Comment by joncoop** [comment]
I pushed an update out swapping axis 3 & axis 4 on windows. I went this route because I want to keep the class as simple as possible. Also, I have some plans for refactoring and want to deal with that before I add "features" such as axis swapping. I will add a note indicating that it works on windows 10 as well. I'm pretty sure that the wireless issue is Linux only. Closing this issue.
