### ISSUE TITLE
Error Support

### ISSUE THREAD

**Issue by ghost** [joncoop/pygame-xbox360controller#3]
I had been planning to implement controller detection, and I noticed that if there is no joystick, it raises pygame.error
I recommend a custom error to handle it.

**Comment by joncoop** [comment]
I think the best option here is just to do the controller detection/creation in the game loop. I might mess around with the simple_game template a bit later this week if I get some time to code. Going to be a bit too busy the next few days to mess around with fun projects like this.

**Comment by ghost** [comment]
I would like to do that in the simple_game template, but depending on how long and/or complex the code for it is, I may want it in its own class. Possibly have a library for small classes, but they each simplify  code well. With this library, have controller detection, as well as syntax and error handling for it; the library can also be added upon, as well. I have already made a simple joystick error detection, but will upload it soon.

**Comment by ghost** [comment]
the error detection has been implemented
I have added a multiple controller detection function in its own file.
it is in the fork currently, under controller_detection.py
